services:
  # vm-builder-focal:
  #   build: ./
  #   image: qemu-packer-builder:latest
  #   privileged: true
  #   cpus: 4
  #   devices:
  #     - /dev/kvm
  #   volumes:
  #     - "~/.ssh:/app"
  #     - "../:/app"
  #     - "../packer_cache:/app/packer_cache" # Packer Cache for faster builds
  #     - "/usr/share/OVMF/OVMF_CODE.fd:/usr/share/OVMF/OVMF_CODE.fd"
  #   environment:
  #     PACKER_LOG: 1
  #   network_mode: host
  #   command:
  #     - make build-focal
  vm-builder-jammy:
    build: ./
    image: qemu-packer-builder:latest
    privileged: true
    cpus: 4
    # devices:
    #   - /dev/kvm
    volumes:
      - "../:/app"
      - "/Users/ali.hussain/.ssh:/root/.ssh"
      - "../packer_cache:/app/packer_cache" # Packer Cache for faster builds
      # - "/usr/share/OVMF/OVMF_CODE.fd:/usr/share/OVMF/OVMF_CODE.fd"
    environment:
      PACKER_LOG: 1
    network_mode: host
    command:
      - packer build -var-file=credentials.pkrvars.hcl ubuntu-server-jammy/ubuntu-server-jammy.pkr.hcl
