---
- hosts: all
  tasks:
    - name: Configure repositories
      block:
        - name: Add pve-no-subscription repo
          ansible.builtin.replace:
            path: /etc/apt/sources.list.d/pve-enterprise.list
            regexp: "^deb https://enterprise.proxmox.com/debian/pve"
            replace: "# deb https://enterprise.proxmox.com/debian/pve"
        - name: Add community repo
          ansible.builtin.apt_repository:
            repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
            state: present
            filename: pve-community.list

    - name: Update system and reboot
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
      notify: reboot_server

    - name: Configure GRUB parameters
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on"' # Removed  init_on_alloc=0
      notify: reboot_server

    - name: Configure SSH hardening
      ansible.builtin.ssh_config:
        section: All
        option: AllowTcpForwarding
        value: "no"
      when: "'sshd' in ansible_facts.packages"

    - name: Create admin user with sudo
      ansible.builtin.user:
        name: "{{ admin_user }}"
        groups: sudo
        ssh_key: "ssh-ed25519 AAAAC3Nz..." # Add your SSH public key


    # - name: Disable root SSH access
    #   ansible.builtin.lineinfile:
    #     path: /etc/ssh/sshd_config
    #     regexp: '^PermitRootLogin'
    #     line: 'PermitRootLogin no'
    #   notify: restart_ssh
