---
- hosts: kubernetes_nodes
  vars:
    ssh_public_key: "{{ lookup('file', '/root/.ssh/id_ed25519.pub') }}"
    # ssh_allowed_ips: ["192.168.1.0/24"]
  tasks:
  - name: Check connectivity
    ansible.builtin.command: echo 'Created using Ansible' >> /etc/hello.txt
    register: connectivity

  - name: Debugging the variable
    ansible.builtin.debug:
      var: connectivity